import { StyleSheet, Dimensions } from 'react-native';

// Shared styles for the admin dashboard and its extracted tab components.
// Moved out of app/(admin)/dashboard.tsx (2769 -> 800 lines) so each
// AdminXxxTab can be a small, focused component that shares a single
// dark-mode design system.
const { width } = Dimensions.get('window');

export const adminStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111827',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#9CA3AF',
    marginTop: 12,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 10,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  logoutButton: {
    padding: 8,
  },
  tabContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    marginHorizontal: 4,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  activeTab: {
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
  },
  tabText: {
    fontSize: 12,
    color: '#9CA3AF',
    marginLeft: 4,
  },
  activeTabText: {
    color: '#6366F1',
    fontWeight: '600',
  },
  tabBadge: {
    position: 'absolute',
    top: -6,
    right: -10,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#EF4444',
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#0F172A',
  },
  tabBadgeWarn: {
    backgroundColor: '#F59E0B',
  },
  tabBadgeCritical: {
    backgroundColor: '#EF4444',
  },
  tabBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '700',
    lineHeight: 12,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 16,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 20,
  },
  statCard: {
    width: (width - 48) / 2,
    padding: 16,
    borderRadius: 12,
    margin: 4,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
  },
  statLabel: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.8)',
    marginTop: 4,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 12,
  },
  riskBars: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
  },
  riskBarItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  riskBarLabel: {
    width: 60,
    fontSize: 12,
    color: '#9CA3AF',
    textTransform: 'capitalize',
  },
  riskBarBg: {
    flex: 1,
    height: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 10,
    overflow: 'hidden',
  },
  riskBarFill: {
    height: '100%',
    borderRadius: 10,
  },
  riskBarCount: {
    width: 40,
    textAlign: 'right',
    fontSize: 12,
    color: '#fff',
    fontWeight: '600',
  },
  universityCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
  },
  universityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  universityName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    flex: 1,
  },
  universityStudents: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  universityStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  uniStat: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  uniStatText: {
    fontSize: 12,
    color: '#9CA3AF',
    marginLeft: 4,
  },
  alertSummary: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  alertSummaryCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 4,
    borderLeftWidth: 3,
    alignItems: 'center',
  },
  alertSummaryValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  alertSummaryLabel: {
    fontSize: 10,
    color: '#9CA3AF',
    marginTop: 4,
  },
  emptyState: {
    alignItems: 'center',
    padding: 40,
  },
  emptyStateText: {
    color: '#9CA3AF',
    marginTop: 12,
  },
  alertCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
  },
  alertHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  alertUser: {
    flex: 1,
  },
  alertUserName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  alertUserEmail: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  alertBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  alertBadgeText: {
    fontSize: 10,
    fontWeight: '600',
  },
  alertMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  alertSource: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  alertDate: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  alertKeywords: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  keywordTag: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginRight: 6,
    marginBottom: 4,
  },
  keywordText: {
    fontSize: 10,
    color: '#EF4444',
  },
  alertContent: {
    fontSize: 13,
    color: '#9CA3AF',
    lineHeight: 18,
    marginBottom: 12,
  },
  acknowledgeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  acknowledgeText: {
    fontSize: 12,
    color: '#10B981',
    marginLeft: 6,
  },
  filterSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  filterLabel: {
    fontSize: 14,
    color: '#9CA3AF',
    marginRight: 12,
  },
  filterButtons: {
    flexDirection: 'row',
  },
  filterButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.05)',
    marginRight: 8,
  },
  filterButtonActive: {
    backgroundColor: '#6366F1',
  },
  filterButtonText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  filterButtonTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  trendChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 150,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 12,
  },
  trendBar: {
    flex: 1,
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  trendBarFill: {
    width: 12,
    borderRadius: 6,
    minHeight: 4,
  },
  trendBarLabel: {
    fontSize: 8,
    color: '#9CA3AF',
    marginTop: 4,
  },
  chartNote: {
    fontSize: 11,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 8,
  },
  analyzeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6366F1',
    paddingVertical: 14,
    borderRadius: 12,
    marginBottom: 16,
  },
  analyzeButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 8,
  },
  analysisResults: {
    marginTop: 12,
  },
  aiInsightsCard: {
    marginTop: 12,
    backgroundColor: '#EEF2FF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#C7D2FE',
    padding: 14,
  },
  aiInsightsText: {
    fontSize: 14,
    lineHeight: 21,
    color: '#3730A3',
  },
  analysisResultsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#EF4444',
    marginBottom: 8,
  },
  analysisCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  analysisHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  analysisName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  riskBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  riskBadgeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  analysisDetail: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 4,
  },
  exportNote: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 20,
    lineHeight: 20,
  },
  exportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  exportIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  exportInfo: {
    flex: 1,
  },
  exportTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  exportDesc: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  // University tab styles
  sectionSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 16,
  },
  universitySelectCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
  },
  universitySelectCardActive: {
    backgroundColor: 'rgba(99, 102, 241, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.3)',
  },
  universitySelectInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  universitySelectIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  universitySelectText: {
    flex: 1,
  },
  universitySelectName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  universitySelectCount: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  universitySelectActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  universityAnalyzeBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedUniversitySection: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  selectedUniversityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  selectedUniversityTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    flex: 1,
  },
  runAnalysisBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#6366F1',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  runAnalysisBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  analysisResultCard: {
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.2)',
  },
  analysisScoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  analysisScoreLabel: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  analysisScoreValue: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  analysisSummary: {
    fontSize: 14,
    color: '#D1D5DB',
    lineHeight: 20,
    marginBottom: 12,
  },
  analysisConcerns: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 8,
    padding: 12,
  },
  analysisConcernsTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#EF4444',
    marginBottom: 8,
  },
  analysisConcernItem: {
    fontSize: 13,
    color: '#F87171',
    marginBottom: 4,
  },
  studentListTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 12,
  },
  studentCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderLeftWidth: 3,
  },
  studentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  studentName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    flex: 1,
  },
  studentEmail: {
    fontSize: 12,
    color: '#9CA3AF',
    marginBottom: 8,
  },
  studentStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  studentStatItem: {
    fontSize: 11,
    color: '#6B7280',
  },
  // Safeguarding analysis styles
  alertActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  analyzeStudentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  analyzeStudentText: {
    fontSize: 12,
    color: '#6366F1',
    fontWeight: '600',
  },
  safeguardingUniversitySection: {
    marginTop: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  noUniversitiesText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    paddingVertical: 20,
  },
  universityQuickList: {
    marginBottom: 16,
  },
  universityQuickCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  universityQuickInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  universityQuickName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#fff',
    flex: 1,
  },
  universityQuickCount: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  analyzeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6366F1',
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  analyzeAllButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  // Subscription Stats Styles
  subscriptionCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
  },
  subscriptionRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  subscriptionItem: {
    alignItems: 'center',
    flex: 1,
  },
  subscriptionValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginTop: 8,
  },
  subscriptionLabel: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 4,
  },
  subscriptionDivider: {
    width: 1,
    height: 50,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  // Section Header Row
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionSubcount: {
    fontSize: 12,
    color: '#6B7280',
  },
  // University Stats Card Styles
  universityStatCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  universityStatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  universityStatIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(99, 102, 241, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  universityStatInfo: {
    flex: 1,
  },
  universityStatName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  universityStatTotal: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  universityStatBar: {
    height: 6,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 8,
  },
  universityStatBarFill: {
    height: '100%',
    borderRadius: 3,
    minWidth: 4,
  },
  universityStatFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  universityStatPremium: {
    fontSize: 11,
    color: '#F59E0B',
  },
  universityStatFree: {
    fontSize: 11,
    color: '#6B7280',
  },
  // AI Learning Styles
  aiStatsContainer: {
    marginBottom: 20,
  },
  aiStatRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  aiStatCard: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  aiStatValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  aiStatLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#D1D5DB',
    marginBottom: 2,
  },
  aiStatSub: {
    fontSize: 11,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  aiSection: {
    marginBottom: 24,
  },
  aiSectionHeader: {
    marginBottom: 16,
  },
  aiSectionDesc: {
    fontSize: 13,
    color: '#9CA3AF',
    marginBottom: 16,
  },
  keywordFilterRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  keywordFilterBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  keywordFilterBtnActive: {
    backgroundColor: '#6366F1',
  },
  keywordFilterText: {
    fontSize: 13,
    color: '#9CA3AF',
  },
  keywordFilterTextActive: {
    color: '#fff',
    fontWeight: '600',
  },
  keywordCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  keywordHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  riskBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  riskBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
  },
  keywordFrequency: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  keywordText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 8,
  },
  keywordContext: {
    fontSize: 12,
    color: '#6B7280',
    fontStyle: 'italic',
    marginBottom: 8,
  },
  keywordConfidence: {
    fontSize: 11,
    color: '#9CA3AF',
    marginBottom: 12,
  },
  keywordActions: {
    flexDirection: 'row',
    gap: 12,
  },
  keywordActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
  },
  approveBtn: {
    backgroundColor: '#10B981',
  },
  rejectBtn: {
    backgroundColor: '#EF4444',
  },
  keywordActionText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    fontSize: 16,
    color: '#9CA3AF',
    marginTop: 12,
  },
  emptyStateSubtext: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 4,
    textAlign: 'center',
  },
  insightCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  insightTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  newBadge: {
    backgroundColor: '#EF4444',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  newBadgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#fff',
  },
  insightDesc: {
    fontSize: 13,
    color: '#D1D5DB',
    lineHeight: 20,
    marginBottom: 8,
  },
  insightTime: {
    fontSize: 11,
    color: '#6B7280',
  },
  reviewBtn: {
    marginTop: 12,
    paddingVertical: 8,
    alignItems: 'center',
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    borderRadius: 8,
  },
  reviewBtnText: {
    fontSize: 13,
    color: '#818CF8',
    fontWeight: '600',
  },
  feedbackCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  feedbackHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  feedbackName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  feedbackSource: {
    fontSize: 12,
    color: '#9CA3AF',
    textTransform: 'capitalize',
  },
  feedbackContent: {
    fontSize: 13,
    color: '#D1D5DB',
    marginBottom: 8,
  },
  feedbackKeywords: {
    fontSize: 11,
    color: '#F59E0B',
    marginBottom: 12,
  },
  feedbackActions: {
    flexDirection: 'row',
    gap: 12,
  },
  feedbackBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    gap: 6,
  },
  truePositiveBtn: {
    backgroundColor: '#10B981',
  },
  falsePositiveBtn: {
    backgroundColor: '#6B7280',
  },
  feedbackBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  analyzeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6366F1',
    paddingVertical: 14,
    borderRadius: 12,
    marginBottom: 24,
    gap: 8,
  },
  analyzeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  miniChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: 100,
    marginTop: 16,
    paddingHorizontal: 8,
  },
  miniChartBar: {
    alignItems: 'center',
    flex: 1,
  },
  miniChartBarFill: {
    width: 24,
    borderRadius: 4,
    marginBottom: 8,
    minHeight: 4,
  },
  miniChartLabel: {
    fontSize: 10,
    color: '#9CA3AF',
  },
  exportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 16,
    gap: 8,
  },
  exportButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
